Meine_Aufgabenliste/Controllers/AdminController.cs
using Meine_Aufgabenliste.Models;
using Meine_Aufgabenliste.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Meine_Aufgabenliste.Controllers {
    public class AdminController : Controller {
        /*
            private readonly ApplicationDbContext _context;

            public AdminController(ApplicationDbContext context) {
                _context = context;
            }
        */

        public IActionResult BenutzerVerwaltung() {

            return View("Benutzer/Verwaltung");
        }

        public IActionResult KategorienVerwaltung() {

            List<Kategorie> kategorien = new List<Kategorie>();

            using (var context = new ApplicationDbContext()) {
                if (context.Kategorie != null) {
                    kategorien = context.Kategorie.ToList();
                }
            }

            ViewBag.Kategorien = kategorien;

            return View("Kategorien/Verwaltung");
        }

        [HttpPost]
        public IActionResult ErstelleKategorie(Kategorie kategorie) {

            using (var context = new ApplicationDbContext()) {
                if (ModelState.IsValid) {
                    context.Add(kategorie);
                    context.SaveChanges();
                }
            }

            return RedirectToAction("KategorienVerwaltung");
        }

        public IActionResult SchluesselwoerterVerwaltung() {

            List<Kategorie> kategorien = new List<Kategorie>();
            using (var context = new ApplicationDbContext()) {
                kategorien = context.Kategorie.ToList();
            }
            ViewBag.Kategorien = kategorien;

            List<Schluesselwort> schluesselwoerter = new List<Schluesselwort>();
            using (var context = new ApplicationDbContext()) {
                schluesselwoerter = context.Schluesselwort.ToList();
            }
            ViewBag.Schluesselwoerter = schluesselwoerter;

            return View("Schluesselwoerter/Verwaltung");
        }
    
        [HttpPost]
        public IActionResult ErstelleSchluesselwort(Schluesselwort schluesselwort) {

            using (var context = new ApplicationDbContext()) {
                using (var transaction = context.Database.BeginTransaction()) {
                    try {
                        //schluesselwort.Kategorie = context.Kategorie.FirstOrDefault(k => k.Id == schluesselwort.KategorieId);

                        context.Add(schluesselwort);
                        context.SaveChanges();

                        transaction.Commit();
                    }
                    catch (Exception ex) {
                        transaction.Rollback();
                        ModelState.AddModelError("", "Fehler beim Speichern des Schluesselworts.");

                        return View("Schluesselwoerter/Verwaltung");
                    }
                }
            }
            
            return RedirectToAction("SchluesselwoerterVerwaltung");
        }

        public IActionResult VerantwortlicheVerwaltung() {

            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();

            using (var context = new ApplicationDbContext()) {
                if (context.Verantwortlicher != null) {
                    verantwortliche = context.Verantwortlicher.ToList();
                }
                else {
                    Console.WriteLine("DbSet<Verantwortlicher> is null");
                }
            }

            ViewBag.Verantwortliche = verantwortliche;

            return View("Verantwortliche/Verwaltung");
        }

        [HttpPost]
        public IActionResult ErstelleVerantwortlicher(Verantwortlicher verantwortlicher) {

            using (var context = new ApplicationDbContext()) {
                if (ModelState.IsValid) {
                    context.Add(verantwortlicher);
                    context.SaveChanges();
                }
            }

            return RedirectToAction("VerantwortlicheVerwaltung");
        }

        public IActionResult StatusVerwaltung() {

            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                if (context.Status != null) {
                    status = context.Status.ToList();
                }
            }

            ViewBag.Status = status;

            return View("Status/Verwaltung");
        }

        [HttpPost]
        public IActionResult ErstelleStatus(Status status) {

            using (var context = new ApplicationDbContext()) {
                if (ModelState.IsValid) {
                    context.Add(status);
                    context.SaveChanges();
                }
            }

            return RedirectToAction("StatusVerwaltung");
        }
    }
}

Meine_Aufgabenliste/Controllers/ToDosController.cs
using Meine_Aufgabenliste.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Meine_Aufgabenliste.Controllers {
    public class ToDosController : Controller {

        public IActionResult Index() {

            List<ToDo> toDos = new List<ToDo>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                    .Include(t => t.Kategorie)
                    .Include(t => t.Schluesselwort)
                    .Include(t => t.Verantwortlicher)
                    .Include(t => t.Status)
                    .ToList();

                ViewBag.ToDos = toDos;
                ViewBag.Kategorien = context.Kategorie.ToList();
                ViewBag.Schluesselwoerter = context.Schluesselwort.ToList();
                ViewBag.Verantwortliche = context.Verantwortlicher.ToList();
                ViewBag.Status = context.Status.ToList();
                ViewBag.Color = "dark";
            }

            return View();
        }

        public IActionResult ToDos_Offen() {
            string title = "Offene Aufgaben";
            ViewBag.Title = title;

            List<ToDo> toDos = new List<ToDo>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                       .Include(toDo => toDo.Kategorie)
                       .Include(toDo => toDo.Schluesselwort)
                       .Include(toDo => toDo.Verantwortlicher)
                       .Include(toDo => toDo.Status)
                       .Where(toDo => toDo.Status.Name == "Offen")
                       .ToList();

                // Laden der Verantwortlichen und Status für Dropdowns
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
            }

            ViewBag.ToDos = toDos;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.Color = "danger";

            return View("Index");
        }

        public IActionResult ToDos_inBearbeitung() {
            string title = "Aufgaben in Bearbeitung";
            ViewBag.Title = title;

            List<ToDo> toDos = new List<ToDo>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                       .Include(toDo => toDo.Kategorie)
                       .Include(toDo => toDo.Schluesselwort)
                       .Include(toDo => toDo.Verantwortlicher)
                       .Include(toDo => toDo.Status)
                       .Where(toDo => toDo.Status.Name == "in Bearbeitung")
                       .ToList();

                // Laden der Verantwortlichen und Status für Dropdowns
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
            }

            ViewBag.ToDos = toDos;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.Color = "warning";

            return View("Index");
        }

        public IActionResult ToDos_Wartend() {
            string title = "Wartende Aufgaben";
            ViewBag.Title = title;

            List<ToDo> toDos = new List<ToDo>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                       .Include(toDo => toDo.Kategorie)
                       .Include(toDo => toDo.Schluesselwort)
                       .Include(toDo => toDo.Verantwortlicher)
                       .Include(toDo => toDo.Status)
                       .Where(toDo => toDo.Status.Name == "Wartend")
                       .ToList();

                // Laden der Verantwortlichen und Status für Dropdowns
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
            }

            ViewBag.ToDos = toDos;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.Color = "primary";

            return View("Index");
        }

        public IActionResult ToDos_Abgeschlossen() {
            string title = "Abgeschlossene Aufgaben";
            ViewBag.Title = title;

            List<ToDo> toDos = new List<ToDo>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                       .Include(toDo => toDo.Kategorie)
                       .Include(toDo => toDo.Schluesselwort)
                       .Include(toDo => toDo.Verantwortlicher)
                       .Include(toDo => toDo.Status)
                       .Where(toDo => toDo.Status.Name == "Abgeschlossen")
                       .ToList();

                // Laden der Verantwortlichen und Status für Dropdowns
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
            }

            ViewBag.ToDos = toDos;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.Color = "success";

            return View("Index");
        }

        public IActionResult ToDos_Archiv() {
            string title = "Archivierte Aufgaben";
            ViewBag.Title = title;

            List<ToDo> toDos = new List<ToDo>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();

            using (var context = new ApplicationDbContext()) {
                toDos = context.ToDo
                       .Include(toDo => toDo.Kategorie)
                       .Include(toDo => toDo.Schluesselwort)
                       .Include(toDo => toDo.Verantwortlicher)
                       .Include(toDo => toDo.Status)
                       .Where(toDo => toDo.Status.Name == "Archiviert")
                       .ToList();

                // Laden der Verantwortlichen und Status für Dropdowns
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
            }

            ViewBag.ToDos = toDos;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.Color = "light";

            return View("Index");
        }

        public IActionResult CreateToDo() {

            List<Kategorie> kategorien = new List<Kategorie>();
            List<Schluesselwort> schluesselwoerter = new List<Schluesselwort>();
            List<Verantwortlicher> verantwortliche = new List<Verantwortlicher>();
            List<Status> status = new List<Status>();
            int nextId = 0; // zum Speichern der nächstfreien Id für neues ToDo

            using (var context = new ApplicationDbContext()) {
                kategorien = context.Kategorie.ToList();
                schluesselwoerter = context.Schluesselwort.ToList();
                verantwortliche = context.Verantwortlicher.ToList();
                status = context.Status.ToList();
                nextId = context.ToDo.Count() + 1;
            }

            ViewBag.Kategorien = kategorien;
            ViewBag.Schluesselwoerter = schluesselwoerter;
            ViewBag.Verantwortliche = verantwortliche;
            ViewBag.Status = status;
            ViewBag.NextId = nextId;

            return View();
        }

        [HttpPost]
        public IActionResult CreateToDo(ToDo toDo) {

            if (!ModelState.IsValid) {
                using (var context = new ApplicationDbContext()) {
                    using (var transaction = context.Database.BeginTransaction()) {
                        try {
                            toDo.Kategorie = context.Kategorie.FirstOrDefault(k => k.Id == toDo.KategorieId);
                            toDo.Schluesselwort = context.Schluesselwort.FirstOrDefault(s => s.Id == toDo.SchluesselwortId);
                            toDo.Verantwortlicher = context.Verantwortlicher.FirstOrDefault(v => v.Id == toDo.VerantwortlicherId);
                            toDo.Status = context.Status.FirstOrDefault(st => st.Id == toDo.StatusId);

                            context.Add(toDo);
                            context.SaveChanges();

                            transaction.Commit();
                        }
                        catch (Exception ex) {
                            transaction.Rollback();
                            ModelState.AddModelError("", "Fehler beim Speichern des ToDos.");

                            // ViewBag-Daten wieder zurückgeben und zur CreateToDo-Maske zurückkehren
                            ViewBag.Kategorien = context.Kategorie.ToList();
                            ViewBag.Schluesselwoerter = context.Schluesselwort.ToList();
                            ViewBag.Verantwortliche = context.Verantwortlicher.ToList();
                            ViewBag.Status = context.Status.ToList();
                            return View("CreateToDo", toDo);
                        }
                    }
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditToDo(ToDo? toDo) {

            using (var context = new ApplicationDbContext()) {
                try {
                    toDo = context.ToDo.FirstOrDefault(t => t.Id == toDo.Id);

Meine_Aufgabenliste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meine_Aufgabenliste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meine_Aufgabenliste.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-latest.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark bg-gradient border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="ToDos" asp-action="Index">Meine Aufgabenliste</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="ToDos" asp-action="ToDos_Offen">Offen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="ToDos" asp-action="ToDos_inBearbeitung">In Bearbeitung</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="ToDos" asp-action="ToDos_Wartend">Wartend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" asp-area="" asp-controller="ToDos" asp-action="ToDos_Abgeschlossen">Abgeschlossen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ToDos" asp-action="ToDos_Archiv">Archiv</a>
                        </li>
                    </ul>
                    <ul class="nav nav-pills">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Admin-Verwaltung</a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Admin" asp-action="KategorienVerwaltung" class="dropdown-item">Kategorien</a></li>
                                <li><a asp-controller="Admin" asp-action="SchluesselwoerterVerwaltung" class="dropdown-item">Schlüsselwörter</a></li>
                                <li><a asp-controller="Admin" asp-action="VerantwortlicheVerwaltung" class="dropdown-item">Verantwortliche</a></li>
                                <li><a asp-controller="Admin" asp-action="StatusVerwaltung" class="dropdown-item">Status</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a asp-controller="Admin" asp-action="BenutzerVerwaltung" class="dropdown-item">Benutzer</a></li>
                            </ul>
                        </li>
                    </ul>
                    <p class="nav navbar-text text-light">@User.Identity?.Name</p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark bg-gradient">
        <div class="container text-center">
            &copy; 2024 Meine Aufgabenliste - Lukas Görzen
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Meine_Aufgabenliste/Views/Shared/_Table.cshtml
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meine_Aufgabenliste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meine_Aufgabenliste.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="text-center mb-5">Meine offenen ToDos</h1>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-light table-hover table-bordered">
            <thead class="table-primary">
                <tr>
                    <th>Id</th>
                    <th>Kategorie</th>
                    <th>Schlüsselwort</th>
                    <th>Aufgabe</th>
                    <th>Beschreibung</th>
                    <th>Lösung</th>
                    <th>Verantwortlich</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @{
                    // foreach (ToDo toDo in ViewBag.ToDos) {
                    <tr>
                        <td>toDo.Id</td>
                        <td>Kategorie</td>
                        <td>Schlüsselwort</td>
                        <td>toDo.Aufgabe</td>
                        <td>toDo.Beschreibung</td>
                        <td>Lösung</td>
                        <td>Verantwortlich</td>
                        <td>Status</td>
                        <td>
                            <div class="col mb-2">
                                <div class="d-flex">
                                    <form asp-action="EditToDo" asp-route-id="toDo.Id" class="me-2">
                                        <button class="btn btn-secondary" type="submit">
                                            <i class="bi bi-pencil"></i>
                                        </button>
                                    </form>
                                    <form asp-action="DeleteToDo" asp-route-id="toDo.Id">
                                        <button class="btn btn-danger" type="submit">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
                }
            </tbody>

            <tfoot>
                <tr class="table">
                    <form asp-action="CreateEditToDo" method="post">
                    <td><input hidden /></td>
                    <td><input placeholder="Aufgabe" class="form-control" /></td>
                    <td><input placeholder="Beschreibung" class="form-control" /></td>
                    <td>
                        <button class="btn btn-success" type="submit">
                            <i class="bi bi-plus-circle"></i>
                        </button>
                    </td>
                    </form>
                </tr>
            </tfoot>
        </table>
    </div>
</body>
</html>